### ISSUE TITLE
Failing Local Builds

### ISSUE THREAD

**Issue by murageden** [andela/mrm-mobile#121]
Title:
Failing Local Builds

Description:
When the build command is run, it results in this error:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:validateSigningMockRelease'.
> Keystore file '/Users/andela/AndroidStudioProjects/mrm-mobile/keystore.jks' not found for signing config 'release'.

Steps To Reproduce:
- Run the `./gradlew build` command in the terminal of your IDE.

Resources:
![image](https://user-images.githubusercontent.com/22506247/45077338-964e7380-b0f5-11e8-9490-1b74d3858102.png)

**Comment by murageden** [comment]
**Solution**
To fix this, change the path of the `storeFile` on the `keystore.properties` file to:
`keystores/keystore.jks`

**Screenshot**
![image](https://user-images.githubusercontent.com/22506247/45077655-6358af80-b0f6-11e8-82e4-2e4bbfc5fab7.png)

**Comment by TheDancerCodes** [comment]
Hi @murageden 

Thank you for the proposed fix. 
I am reaching out to @daddychukz to update the file pinned in our slack channel.
